language : python

python :
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_script :
  - pip install -r requirement.txt

script :
  - cd test
  - coverage run test_pygiftparser.py

after_success:
  - coveralls
