language : python

python :
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_script :
  - pip install -r requirement.txt

script :
  - cd tests
  - coverage run parsergift_test.py

after_success:
  - coveralls
